# Build stage
FROM node:20-alpine as build

WORKDIR /app

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Production stage
FROM nginx:1.27-alpine

COPY --from=build /app/build /usr/share/nginx/html

# add custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
