services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
